import {
  Users, UserPlus, Layers, BookOpen, UserCheck, ListChecks, Target, CalendarDays,
  ClipboardList, Percent, GraduationCap, RefreshCw, FileText, Book, History,
  FolderOpen, FileBadge, ScrollText, HeartHandshake, MessageSquareText, Award,
  BarChart3, GitCompare, Map, Send, Scale, ShieldAlert, Sparkles, Building2,
  UserCog, ClipboardCheck, Grid3x3, Settings, Image as ImageIcon, GitMerge,
  ArrowLeftRight, Inbox, FileClock, UsersRound, CalendarClock, LineChart,
  Milestone, Table2, CalendarCheck, Network, Repeat, KeyRound, Activity,
  Archive, ArrowLeft, BadgeCheck, BellRing, BookMarked, BookPlus, CalendarCheck2, CalendarRange, ClipboardPenLine, Compass, Crown, FilePenLine, FileSpreadsheet, Files, FlaskConical, FolderCheck, Folders, Gauge, Globe, Handshake, Home, Landmark, LayoutGrid, Library, LibraryBig, NotebookPen, Package, Presentation, Route, Shuffle, Split, Stamp, TableProperties, Tags, TriangleAlert, Trophy, Upload, UserRoundCog, UserRoundPlus, UserSearch, Wallet, Wrench,
  type LucideIcon,
} from "lucide-react";

// Keyed by exact nav label — a small, deliberate set of icons rather
// than a different one per page, since consistently reusing the same
// icon for the same *kind* of thing (all reports get BarChart3, all
// course lists get BookOpen, etc.) reads faster than novelty would.
const ICONS_BY_LABEL: Record<string, LucideIcon> = {
  "Faculty Onboarding": UserPlus,
  "Degree Programs & Batches": Layers,
  "Courses": BookOpen,
  "Assign Subject Experts": UserCheck,
  "Elective Options": ListChecks,
  "Program Learning Outcomes": Target,
  "Current Semester": CalendarDays,
  "Timetable": Table2,
  "Calendar & Exam Dates": CalendarClock,
  "Students": Users,
  "Repeat/Summer Offering": Repeat,
  "Grading Scale": Percent,
  "Assignment History": History,
  "Report Bundles": FolderOpen,
  "Program Document": FileBadge,
  "Required Textbooks": Book,
  "Student Transcript": ScrollText,
  "Alumni & Employers": HeartHandshake,
  "Feedback Surveys": MessageSquareText,
  "Teacher Load Report": BarChart3,
  "Semester Health": Activity,
  "Batch Comparison": GitCompare,
  "Prerequisite Map": Map,
  "Prerequisite Correlation": Map,
  "Feed-Forward Digest": Send,
  "Weight Policy": Scale,
  "Weight Exceptions": ShieldAlert,
  "AI Configuration": Sparkles,
  "Alumni Data Custodian": UserCog,
  "CQI Records": ClipboardCheck,
  "PLO–Course Matrix": Grid3x3,
  "Platform Settings": Settings,
  "Landing Page": ImageIcon,
  "Curriculum Migration": GitMerge,
  "Version Migration": GitMerge,
  "Master Curricula": Layers,
  "Master Curriculum": Layers,
  "Course Repositioning": ArrowLeftRight,
  "Course Equivalence": ArrowLeftRight,
  "Course Short Names": Book,
  "Content Sync": RefreshCw,
  "Import Course Content": Inbox,
  "Review Queue": Inbox,
  "OMC Members": UsersRound,
  "OMC Reports": FileText,
  "Reports": FileText,
  "Report Access Control": KeyRound,
  "Audit Log": FileClock,
  "Institute Head Accounts": Building2,
  "Manage Institute Heads": Building2,
  "Course Assigners": UserCog,
  "Program Coordinators": UserCog,
  "Section Assignment Matrix": Network,
  "Instructor Delivery Review": ClipboardList,
  "My Assigned Courses": BookOpen,
  "My Semester Courses": CalendarCheck,
  "My Course Priorities": Award,
  "My Availability": CalendarDays,
  "Cross-Instructor Comparison": GitCompare,
  "Section Comparison": GitCompare,
  "Total Summary": LineChart,
  "Passing Criteria": Milestone,
  "Approved & Assigned": ClipboardCheck,
  "Approved, No Course Assigned": ClipboardList,
  // Pages added later: same rule, one icon per kind of thing.
  "Home": Home,
  "Needs Attention": BellRing,
  "Requests": Inbox,
  "Deadlines": CalendarClock,
  "Approvals": Stamp,
  "My Profile": UserCog,
  "My Faculty": Landmark,
  "My Department": Building2,
  "My Programs": LayoutGrid,
  "My Labs": FlaskConical,
  "My Master Courses": BookMarked,
  "My Timetable": Table2,
  "My Transcript": FileText,
  "My OBE Progress": Gauge,
  "Advisor Dashboard": Compass,
  "Colleagues’ Plans": NotebookPen,
  "Teacher Work Progress": Activity,
  "Yearly Summary": CalendarCheck2,
  "Academic Calendar": CalendarRange,
  "Admission Criteria": ClipboardPenLine,
  "Account Requests": UserRoundPlus,
  "Accreditation Evidence": FolderCheck,
  "Accreditation Overview": BadgeCheck,
  "Accreditation Status": BadgeCheck,
  "Evidence Files": Files,
  "Course Folders": Folders,
  "Meetings & Minutes": Presentation,
  "Resources": Package,
  "Extra-curricular Activities": Trophy,
  "Graduation & Surveys": GraduationCap,
  "Finance": Wallet,
  "Lab Inventory": FlaskConical,
  "Lab Engineers": Wrench,
  "Library Inventory": Library,
  "Public Course Library": Globe,
  "All Users and Roles": UsersRound,
  "All users": UsersRound,
  "People & Roles": UsersRound,
  "OMC members": UsersRound,
  "Course Teams": UsersRound,
  "Program Leads": UserCog,
  "Manage Chairmen": UserRoundCog,
  "Master Curriculum Experts": UserSearch,
  "Course Leads": Crown,
  "Teacher Onboarding": UserPlus,
  "Teacher Program Moves": ArrowLeftRight,
  "Teachers from Other Departments": Handshake,
  "Move Program Data": ArrowLeftRight,
  "Departments": Building2,
  "Faculties & Deans": Landmark,
  "Institute Chart": Network,
  "Institute chart": Network,
  "Institute Settings": Settings,
  "Curricula": LibraryBig,
  "Curriculum Readiness Matrix": TableProperties,
  "Curriculum vs HEC": Scale,
  "Template Changes": FilePenLine,
  "Course & Teacher Categories": Tags,
  "Course Split": Split,
  "Course Requests": Inbox,
  "Course Registration": BookPlus,
  "Degree Plan": Route,
  "Elective Choices": ListChecks,
  "Elective Instructor Report": BarChart3,
  "Faculty Details Report": FileSpreadsheet,
  "Deficiency Courses Status": TriangleAlert,
  "Out-of-Batch Requests": Shuffle,
  "Historical Grades Upload": Archive,
  "Bulk Student Upload": Upload,
  "Program Semester Map": Map,
  "Semester Section Map": LayoutGrid,
  "Back to Dashboard": ArrowLeft,
};

export function getNavIcon(label: string): LucideIcon {
  return ICONS_BY_LABEL[label] || Milestone;
}
