import {
  Users, UserPlus, Layers, BookOpen, UserCheck, ListChecks, Target, CalendarDays,
  ClipboardList, Percent, GraduationCap, RefreshCw, FileText, Book, History,
  FolderOpen, FileBadge, ScrollText, HeartHandshake, MessageSquareText, Award,
  BarChart3, GitCompare, Map, Send, Scale, ShieldAlert, Sparkles, Building2,
  UserCog, ClipboardCheck, Grid3x3, Settings, Image as ImageIcon, GitMerge,
  ArrowLeftRight, Inbox, FileClock, UsersRound, CalendarClock, LineChart,
  Milestone, Table2, CalendarCheck, Network, Repeat, KeyRound, Activity,
  type LucideIcon,
} from "lucide-react";

// Keyed by exact nav label — a small, deliberate set of icons rather
// than a different one per page, since consistently reusing the same
// icon for the same *kind* of thing (all reports get BarChart3, all
// course lists get BookOpen, etc.) reads faster than novelty would.
const ICONS_BY_LABEL: Record<string, LucideIcon> = {
  "Faculty Onboarding": UserPlus,
  "Degree Programs & Batches": Layers,
  "Courses": BookOpen,
  "Assign Subject Experts": UserCheck,
  "Elective Options": ListChecks,
  "Program Learning Outcomes": Target,
  "Current Semester": CalendarDays,
  "Timetable": Table2,
  "Calendar & Exam Dates": CalendarClock,
  "Students": Users,
  "Repeat/Summer Offering": Repeat,
  "Grading Scale": Percent,
  "Assignment History": History,
  "Report Bundles": FolderOpen,
  "Program Document": FileBadge,
  "Required Textbooks": Book,
  "Student Transcript": ScrollText,
  "Alumni & Employers": HeartHandshake,
  "Feedback Surveys": MessageSquareText,
  "Teacher Load Report": BarChart3,
  "Semester Health": Activity,
  "Batch Comparison": GitCompare,
  "Prerequisite Map": Map,
  "Prerequisite Correlation": Map,
  "Feed-Forward Digest": Send,
  "Weight Policy": Scale,
  "Weight Exceptions": ShieldAlert,
  "AI Configuration": Sparkles,
  "Alumni Data Custodian": UserCog,
  "CQI Records": ClipboardCheck,
  "PLO–Course Matrix": Grid3x3,
  "Platform Settings": Settings,
  "Landing Page": ImageIcon,
  "Curriculum Migration": GitMerge,
  "Version Migration": GitMerge,
  "Master Curricula": Layers,
  "Master Curriculum": Layers,
  "Course Repositioning": ArrowLeftRight,
  "Course Equivalence": ArrowLeftRight,
  "Course Short Names": Book,
  "Content Sync": RefreshCw,
  "Import Course Content": Inbox,
  "Review Queue": Inbox,
  "OMC Members": UsersRound,
  "OMC Reports": FileText,
  "Reports": FileText,
  "Report Access Control": KeyRound,
  "Audit Log": FileClock,
  "Chairman Accounts": Building2,
  "Manage Chairmen": Building2,
  "Course Assigners": UserCog,
  "Program Coordinators": UserCog,
  "Section Assignment Matrix": Network,
  "Instructor Delivery Review": ClipboardList,
  "My Assigned Courses": BookOpen,
  "My Semester Courses": CalendarCheck,
  "My Course Priorities": Award,
  "My Availability": CalendarDays,
  "Cross-Instructor Comparison": GitCompare,
  "Section Comparison": GitCompare,
  "Total Summary": LineChart,
  "Passing Criteria": Milestone,
  "Approved & Assigned": ClipboardCheck,
  "Approved, No Course Assigned": ClipboardList,
};

export function getNavIcon(label: string): LucideIcon {
  return ICONS_BY_LABEL[label] || Milestone;
}
